# ==============================================================================
# HOME MANAGER CONFIGURATION
# ==============================================================================
# Per-user configuration managed by home-manager
# ==============================================================================

{ config, lib, pkgs, username, gitName, gitEmail, ... }:

{
  home-manager.useGlobalPkgs = true;
  home-manager.useUserPackages = true;

  home-manager.users.${username} = { pkgs, lib, ... }: {
    # home-manager state version
    home.stateVersion = "24.05";

    # User-specific packages
    home.packages = with pkgs; [
      fzf
      lazygit
      opencode
    ];

    # --------------------------------------------------------------------------
    # GIT CONFIGURATION
    # --------------------------------------------------------------------------
    programs.git = {
      enable = true;
      ignores = [ ".DS_Store" ];
      settings = {
        user = {
          name = gitName;
          email = gitEmail;
        };
        init.defaultBranch = "main";
        core.editor = "nvim";
        pull.rebase = true;
      };
    };

    # --------------------------------------------------------------------------
    # ZSH & Powerlevel10k Configuration
    # --------------------------------------------------------------------------
    programs.zsh = {
      enable = true;
      enableCompletion = true;
      autosuggestion.enable = true;
      syntaxHighlighting.enable = true;

      shellAliases = {
        # Zen Browser uses profile from ~/Library/Application Support/Zen Browser/
      };

      initContent = ''
        source ${pkgs.fzf}/share/fzf/key-bindings.zsh
        source ${pkgs.fzf}/share/fzf/completion.zsh
        
        # Load powerlevel10k theme
        source ${pkgs.zsh-powerlevel10k}/share/zsh-powerlevel10k/powerlevel10k.zsh-theme
        
        # Source p10k config if it exists
        [[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
      '';

      oh-my-zsh = {
        enable = true;
        theme = "";  # Empty theme - using powerlevel10k instead
        plugins = [ "git" "docker" "fzf" ];
      };
    };

    # Powerlevel10k config
    home.file.".p10k.zsh".source = ../dotfiles/p10k/.p10k.zsh;

    # --------------------------------------------------------------------------
    # DIRENV CONFIGURATION
    # --------------------------------------------------------------------------
    programs.direnv = {
      enable = true;
      enableZshIntegration = true;
      nix-direnv.enable = true;
    };

    # --------------------------------------------------------------------------
    # DOTFILES
    # --------------------------------------------------------------------------
    xdg.configFile = {
      "ghostty/config".source = ../dotfiles/ghostty/config;

      # Sketchybar config (disabled - keeping dotfiles for reference)
      # "sketchybar/sketchybarrc" = {
      #   source = ../dotfiles/sketchybar/sketchybarrc;
      #   executable = true;
      # };
      # "sketchybar/plugins" = {
      #   source = ../dotfiles/sketchybar/plugins;
      #   recursive = true;
      # };
    };

    # App preferences (~/Library/Preferences/)
    home.file = {
      # Stats preferences
      "Library/Preferences/eu.exelban.Stats.plist" = {
        source = ../dotfiles/stats/eu.exelban.Stats.plist;
        force = true;
      };
      
      # Rectangle config
      "Library/Application Support/Rectangle/RectangleConfig.json" = {
        source = ../dotfiles/rectangle/RectangleConfig.json;
        force = true;
      };
      
      # SSH config (public keys are generated dynamically by setup-ssh.sh)
      ".ssh/config" = {
        source = ../dotfiles/ssh/config;
      };
      ".ssh/known_hosts" = {
        source = ../dotfiles/ssh/known_hosts;
      };
      # Note: Public keys are NOT managed here - they're generated by:
      #   - GitHub: `gh auth login` creates id_ed25519.pub
      #   - Bitwarden: setup-ssh.sh generates .pub from private keys
    };

    # Zen Browser profile setup (prefs, CSS, containers, handlers) is handled
    # by post-install.sh after Zen's first-run wizard completes.
  };
}

